//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Bookings = new HashSet<Booking>();
            this.ScheduleTimings = new HashSet<ScheduleTiming>();
        }
    
        public int DoctorId { get; set; }
        public string DoctorName { get; set; }
        public string DoctorPhone { get; set; }
        public string DoctorEmail { get; set; }
        public Nullable<System.DateTime> DoctorDateOfBirth { get; set; }
        public string DoctorDegree { get; set; }
        public string DoctorCollege { get; set; }
        public string DoctorAwards { get; set; }
        public string DoctorProfileImage { get; set; }
        public Nullable<System.DateTime> DoctorMemberSince { get; set; }
        public byte DoctorGender { get; set; }
        public string NationalID { get; set; }
        public string DoctorAbout { get; set; }
        public Nullable<double> InsideServicePrice { get; set; }
        public Nullable<double> OutsideServicePrice { get; set; }
        public int SpecialityFk { get; set; }
        public Nullable<int> CountryFk { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> DoctorIsActive { get; set; }
        public string UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Country Country { get; set; }
        public virtual Speciality Speciality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleTiming> ScheduleTimings { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
