//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        public int MedicationId { get; set; }
        public string MedicationName { get; set; }
        public string MedicationAbout { get; set; }
        public string MedicationImagePath { get; set; }
        public Nullable<bool> MedicationIsActive { get; set; }
    }
}
