//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int PatientId { get; set; }
        public string PatientName { get; set; }
        public string PatientPhone { get; set; }
        public string PatientEmail { get; set; }
        public System.DateTime PatientDateOfBirth { get; set; }
        public string PatientAddress { get; set; }
        public byte PatientGender { get; set; }
        public string NationalID { get; set; }
        public Nullable<double> PatientWeight { get; set; }
        public Nullable<double> PatientsHeight { get; set; }
        public string PatientProfileImage { get; set; }
        public Nullable<byte> BlodGroupFk { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string UserId { get; set; }
    
        public virtual BlodGroup BlodGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
