//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleTiming
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleTiming()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int DrTimingId { get; set; }
        public System.TimeSpan DrTimingSlotFrom { get; set; }
        public System.TimeSpan DrTimingSlotTo { get; set; }
        public byte WeekDayFk { get; set; }
        public int DoctorFk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual WeekDay WeekDay { get; set; }
    }
}
